### ISSUE TITLE
Conda.add("numpy") fails on 64-bit Windows 10

### ISSUE THREAD

**Issue by Asdow** [JuliaPy/Conda.jl#81]
Hello. I was updating my Julia to 0.6 stable but ever since doing that I can't get PyCall to work and I've tracked it down to Conda not working right. First I got stuck on the endless miniconda install loop. After using the workaround in https://github.com/JuliaPy/Conda.jl/issues/79 I managed to install it, but I still can't get it to work. 
Doing 

```
using Conda

Conda.add("numpy")
```

gives this error
```
Traceback (most recent call last):
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 18: ordinal not in range(128)
ERROR: failed process: Process(setenv(`'I:\Julia\Julia_pkgs\v0.6\Conda\deps\usr\Scripts\conda.exe' install -y numpy`,String["USERDOMAIN_ROAMINGPROFILE=DESKTOP-9PHTHQA", "HOMEPATH=\\Users\\Ghost", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "APPDATA=C:\\Users\\Ghost\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-9PHTHQA", "OS=Windows_NT", "PROCESSOR_REVISION=5e03", "TMP=C:\\Users\\Ghost\\AppData\\Local\\Temp", "AF_PATH_v3=C:\\Program Files\\ArrayFire\\v3", "ALLUSERSPROFILE=C:\\ProgramData", "Path=I:\\Julia\\Julia-0.6.0\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static;D:\\Ohjelmat\\Tekstinkäsittelyä\\MikTex\\miktex\\bin\\x64\\;D:\\Ohjelmat\\Matlab2013\\runtime\\win64;D:\\Ohjelmat\\Matlab2013\\bin;D:\\Ohjelmat\\Matlab2013\\polyspace\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Users\\Ghost\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Ghost\\AppData\\Local\\atom\\bin;C:\\Program Files\\ArrayFire\\v3\\lib;I:\\Julia\\Julia-0.6.0\\bin;C:\\Users\\Ghost\\AppData\\Local\\Microsoft\\WindowsApps;", "COMPUTERNAME=DESKTOP-9PHTHQA", "USERNAME=Ghost", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Files\\Common Files", "CONDARC=I:\\Julia\\Julia_pkgs\\v0.6\\Conda\\deps\\usr\\condarc-julia.yml", "USERPROFILE=C:\\Users\\Ghost", "PSModulePath=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\Program Files\\Intel\\", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\Ghost", "SystemDrive=C:", "TEMP=C:\\Users\\Ghost\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "LOCALAPPDATA=C:\\Users\\Ghost\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel", "NUMBER_OF_PROCESSORS=4", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "AF_PATH=C:\\Program Files\\ArrayFire\\v3", "PROMPT=\$P\$G", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\Ghost\\OneDrive", "CONDA_DEFAULT_ENV=I:\\Julia\\Julia_pkgs\\v0.6\\Conda\\deps\\usr", "VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\", "JULIA_HOME=I:\\Julia\\Julia-0.6.0\\bin", "ProgramFiles(x86)=C:\\Program Files (x86)", "JULIA_NUM_THREADS=4", "JULIA_PKGDIR=I:\\Julia\\Julia_pkgs", "=ExitCode=00000000", "LOGONSERVER=\\\\DESKTOP-9PHTHQA", "CONDA_PREFIX=I:\\Julia\\Julia_pkgs\\v0.6\\Conda\\deps\\usr", "windir=C:\\WINDOWS", "FPS_BROWSER_USER_PROFILE_STRING=Default", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at .\process.jl:682
 [2] run(::Cmd) at .\process.jl:651
 [3] add(::String) at I:\Julia\Julia_pkgs\v0.6\Conda\src\Conda.jl:210
```

I have no idea how to fix this and any help would be really appreciated!

**Comment by stevengj** [comment]
Possibly a bug in Anaconda, if it doesn't handle non-ASCII path names?

Or possibly we can fix it by setting the `PYTHONIOENCODING` environment variable to UTF-8?  (We should probably do that anyway.)

**Comment by stevengj** [comment]
It could also be that we are running into https://bugs.python.org/issue2128 … in which case the fix is to switch to Python 3:
```jl
using Conda
rm(Conda.ROOTENV, recursive=true)
ENV["CONDA_JL_VERSION"]=3
Pkg.build("Conda")
```
and then restart Julia and run `Pkg.build("PyCall")`

**Comment by simonbyrne** [comment]
This seems like a related issue:
https://discourse.julialang.org/t/jupyter-notebook/21509

One workaround is to override the Conda directory:
```julia
ENV["CONDA_JL_HOME"] = "C:\conda" # or some other path
using Pkg
pkg"build Conda"
```

**Comment by simonbyrne** [comment]
It may possibly be fixed by this?:
https://github.com/conda/conda/pull/8289

**Comment by epogrebnyak** [comment]
As an update, I still get `UnicodeDecodeError`, maybe should post as a new issue? 

````
julia> Conda.add("numpy")
[ Info: Running `conda install -y numpy` in root environment
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Евгений\.julia\conda\3

  added / updated specs:
    - numpy


The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    icc_rt:          2019.0.0-h0cc432a_1
    intel-openmp:    2019.3-203
    mkl:             2019.3-203
    mkl_fft:         1.0.12-py36h14836fe_0
    mkl_random:      1.0.2-py36h343c172_0
    numpy:           1.16.3-py36h19fb1c0_0
    numpy-base:      1.16.3-py36hc3f5095_0

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0          --> 2019.1.23-0
    certifi:         2018.4.16-py36_0      --> 2019.3.9-py36_0
    conda:           4.5.4-py36_0          --> 4.6.14-py36_0
    cryptography:    2.2.2-py36hfa6e2cd_0  --> 2.6.1-py36h7a1dbc1_0
    openssl:         1.0.2o-h8ea7d77_0     --> 1.1.1b-he774522_1
    vc:              14-h0510ff6_3         --> 14.1-h0510ff6_4
    vs2015_runtime:  14.0.25123-3          --> 14.15.26706-h3a45250_4

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'None'.
UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
Attempting to roll back.

Rolling back transaction: done

UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')


ERROR: failed process: Process(setenv(`'C:\Users\Евгений\.julia\conda\3\Scripts\conda.exe' install -y numpy`,["USERDOMAIN_ROAMINGPROFILE=EP_WIN8", "HOMEPATH=\\Users\\Евгений", "ConEmuBaseDir=D:\\Programs\\Cmder\\vendor\\conemu-maximus5\\ConEmu", "ChocolateyLastPathUpdate=Tue Jan 29 16:21:23 2019", "CMDER_ROOT=D:\\Programs\\Cmder", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.py;.pyw;.RB;.RBW;.RB;.RBW", "SESSIONNAME=Console", "APPDATA=C:\\Users\\Евгений\\AppData\\Roaming", "ConEmuDir=D:\\Programs\\Cmder\\vendor\\conemu-maximus5", "ConEmuBuild=161206", "ConEmuTask={cmd::Cmder}", "ChocolateyToolsLocation=C:\\tools", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=EP_WIN8", "OS=Windows_NT", "PROCESSOR_REVISION=3c03", "TMP=C:\\Users\\B7E3~1\\AppData\\Local\\Temp", "ALLUSERSPROFILE=C:\\ProgramData", "Path=D:\\Programs\\Cmder\\bin;D:\\Programs\\Cmder\\vendor\\conemu-maximus5\\ConEmu\\Scripts;D:\\Programs\\Cmder\\vendor\\conemu-maximus5;D:\\Programs\\Cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\tools\\ruby26\\bin;C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.4.3\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.4.3\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Python33;C:\\Program Files\\doxygen\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files (x86)\\Cyberduck CLI\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\Windows Live\\Shared;D:\\Programs\\julia\\Julia-0.4.5\\bin;C:\\Program Files\\Amazon\\AWSCLI\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\nodejs\\;D:\\Programs\\Go\\bin;D:\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Haskell Platform\\8.4.3\\mingw\\bin;C:\\Program Files (x86)\\Brackets\\command;D:\\Anaconda3;D:\\Anaconda3\\Scripts;D:\\Anaconda3\\Library\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Intel\\Intel(R) Manage;%GOPATH%\\bin;C:\\Program Files\\gretl;C:\\Users\\Евгений\\AppData\\Local\\Julia-1.0.2\\bin;C:\\Users\\Евгений\\AppData\\Local\\hyper\\app-2.0.0\\resources\\bin;C:\\Users\\Евгений\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Евгений\\AppData\\Roaming\\npm;C:\\Users\\Евгений\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Евгений\\AppData\\Local\\atom\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\share\\vim\\vim74;D:\\Programs\\Cmder\\", "COMPUTERNAME=EP_WIN8", "ConEmuHWND=0x000D05E8", "FP_NO_HOST_CHECK=NO", "USERNAME=Евгений", "user-aliases=D:\\Programs\\Cmder\\config\\user-aliases.cmd", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Files\\Common Files", "PLINK_PROTOCOL=ssh", "architecture=64", "CONDARC=C:\\Users\\Евгений\\.julia\\conda\\3\\condarc-julia.yml", "ConEmuBackHWND=0x00050658", "USERPROFILE=C:\\Users\\Евгений", "ConEmuPalette=Monokai", "PSModulePath=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\Евгений\\Desktop", "SVN_SSH=C:\\\\Program Files\\\\Git\\\\bin\\\\ssh.exe", "HOME=C:\\Users\\Евгений", "SystemDrive=C:", "HOMEDRIVE=C:", "TEMP=C:\\Users\\B7E3~1\\AppData\\Local\\Temp", "TERM=cygwin", "PYTHONIOENCODING=UTF-8", "ConEmuServerPID=12708", "LOCALAPPDATA=C:\\Users\\Евгений\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel", "aliases=D:\\Programs\\Cmder\\config\\user-aliases.cmd", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "NUMBER_OF_PROCESSORS=4", "asl.log=Destination=file", "ConEmuConfig=", "ConEmuWorkDir=C:\\Users\\Евгений", "verbose-output=0 ", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "ConEmuANSI=ON", "PROMPT=C\bL\bI\bN\bK\b \b\$P\$G", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\Евгений\\OneDrive", "OneDriveConsumer=C:\\Users\\Евгений\\OneDrive", "ConEmuPID=7076", "ANSICON=132x1000 (132x28)", "ANSICON_DEF=7", "ConEmuHooks=Enabled", "VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\", "=D:=D:\\Programs\\Cmder\\config\\profile.d", "ProgramFiles(x86)=C:\\Program Files (x86)", "ConEmuDrawHWND=0x0002064E", "ChocolateyInstall=C:\\ProgramData\\chocolatey", "=ExitCode=00000000", "GIT_INSTALL_ROOT=C:\\Program Files\\Git", "ConEmuWorkDrive=C:", "LOGONSERVER=\\\\EP_WIN8", "ConEmuAnsiLog=", "CONDA_PREFIX=C:\\Users\\Евгений\\.julia\\conda\\3", "windir=C:\\WINDOWS", "ConEmuArgs2=", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "ConEmuDrive=D:", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1", "GOROOT=D:\\Programs\\Go\\", "ConEmuArgs=/Icon \"D:\\Programs\\Cmder\\icons\\cmder.ico\" /Title Cmder"]), ProcessExited(1)) [1]
Stacktrace:
 [1] run at .\process.jl:661 [inlined]
 [2] macro expansion at .\logging.jl:305 [inlined]
 [3] runconda(::Cmd, ::String) at C:\Users\Евгений\.julia\packages\Conda\uQitS\src\Conda.jl:112
 [4] add at C:\Users\Евгений\.julia\packages\Conda\uQitS\src\Conda.jl:181 [inlined] (repeats 2 times)
 [5] top-level scope at none:0

```

**Comment by stevengj** [comment]
Try removing Julia from the equation:

If you type `CONDA install numpy` in your Windows console, where `CONDA` is replaced by the path you get in Julia from `Conda.conda`, what happens?

**Comment by epogrebnyak** [comment]
> Try removing Julia from the equation:
> 
> If you type `CONDA install numpy` in your Windows console, where `CONDA` is replaced by the path you get in Julia from `Conda.conda`, what happens?

Thanks for pointing to non-Julia call. My conda installation seems to be locked by either python version (chardet) or pip version. 

When running `conda install numpy` I get a similar error stack as in `conda update conda`, which I document [here](https://github.com/conda/conda/issues/8662).

Maybe I have to reinstall conda from a binary file.

**Comment by simonbyrne** [comment]
Does setting the `CONDA_JL_HOME` environment variable solve the problem (it will only affect Conda.jl, not Conda from the command line)

**Comment by epogrebnyak** [comment]
I tried  ```ENV["CONDA_JL_HOME"] = "D:/Anaconda3/Scripts"```, but `Conda.add("numpy")` downloads the dinaries, but still fails with  `UnicodeDecodeError`:

```
UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
Attempting to roll back.

Rolling back transaction: done

UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
```

It seems somewhere Conda.jl is trying to make use of possible `conda` locations on the system and when encouners non-ASCII symbols on path, fails.

**Comment by epogrebnyak** [comment]
The list of path:
 
```
D:\\Anaconda3\\envs\\mxme\r\n
D:\\Anaconda3\\envs\\minimal\r\n
D:\\Anaconda3\\envs\\xl_env\r\n
D:\\Anaconda3\\envs\\maspider\r\n
D:\\Anaconda3\\envs\\spa\r\n
C:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\n
C:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\n
```

Actually, `C:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3` does not even exist on the system and not mentioned in %PATH%.

Wonder which program tries to access it, maybe conda itself?

**Comment by simonbyrne** [comment]
> I tried `ENV["CONDA_JL_HOME"] = "D:/Anaconda3/Scripts"`, but `Conda.add("numpy")` downloads the dinaries, but still fails with `UnicodeDecodeError`:

Try `Pkg.build("Conda")` after setting the environment variable.

**Comment by epogrebnyak** [comment]
> Try removing Julia from the equation:
> 
> If you type `CONDA install numpy` in your Windows console, where `CONDA` is replaced by the path you get in Julia from `Conda.conda`, what happens?

It seems there is an issue on the conda side with encoding. `conda update numpy` or  `conda update conda` fail with `UnicodeDecodeError`. 

Filled an issue with conda: https://github.com/conda/conda/issues/8662

**Comment by epogrebnyak** [comment]
> > I tried `ENV["CONDA_JL_HOME"] = "D:/Anaconda3/Scripts"`, but `Conda.add("numpy")` downloads the binaries, but still fails with `UnicodeDecodeError`:
> 
> Try `Pkg.build("Conda")` after setting the environment variable.

Pkg.build("Conda") worked fine, thank you! My problem is now that building PyCall hangs indefinitely, but that is a separate issue that I will investigate.

**Comment by stevengj** [comment]
Thanks for looking into this.  Closing as an upstream bug.

**Comment by tkf** [comment]
According to https://github.com/conda/conda/issues/8662#issuecomment-492378563 it looks like it is fixed in conda 4.16.  However, we need to fix https://github.com/JuliaPy/Conda.jl/issues/125#issuecomment-423771056 to let people use conda 4.16.

**Comment by stevengj** [comment]
The issue turns out to arise if the user has a leftover `~/.conda/environments.txt` file from an older Conda installation (which used the locale's encoding rather than UTF-8).  The current solution is to delete or re-encode `~/.conda/environments.txt`.
